@ECHO off
Set TSTPLAN=C:\tstPlan\
set LOGFILE=FullLog.txt
SET CSVFILE=Kinetic_MP_DATA.csv
Set PATH=%TESTPLAN%
SET FILELIMIT=1000000
SET BACKSTATUS<BACKUP.TXT
ECHO BACKSTATUS
for /f "delims==" %%i in ("autoclean.cmd") do SET CURRENTPATH=%%~dpi
cd %TSTPLAN%
FOR /F "TOKENS=1,2,3,4 DELIMS= " %%I IN ('DATE /T') DO SET DATECODE=%%I
FOR /F "TOKENS=1,2,3* DELIMS=/" %%I IN ("%DATECODE%") DO SET DATECODE=%%I%%J%%K
ECHO %DATECODE%
FOR /F "TOKENS=1,2,3 DELIMS=." %%I IN ("%LOGFILE%") DO SET NEWFILENAME=%%I
FOR /F "TOKENS=1,2,3 DELIMS=." %%I IN ("%CSVFILE%") DO SET NEWCSVFILENAME=%%I
ECHO %NEWFILENAME%
FOR %%i IN  (%tstplan%%logfile%) DO set SIZEOFLOG=%%~zi
echo %SIZEOFLOG%
IF %SIZEOFLOG% GTR %FILELIMIT% (
rem RENAME %TSTPLAN%%LOGFILE% %NEWFILENAME%%DATECODE%.TXT
RENAME %LOGFILE% %NEWFILENAME%%DATECODE%.TXT
)
RENAME %CSVFILE% %NEWCSVFILENAME%%DATECODE%.CSV
CD %CURRENTPATH%
EXIT 0

