@Echo off
REM Please do not modify this file, this file is generated by C:\Program Files (x86)\Common Files\Logitech\EasyAVRuntimeEngine\EasyVideoCmd.exe
SET Status=0
SET ReturnCode=0
SET Message=Ok!
SET Headers=MyHeader
SET Values=
SET LowLimit=0.0
SET UpLimit=5.0
SET TargetLimit=5.0
SET LogFile=test.log
SET VarResultSummary=
